In [50]:
import numpy as np
arr1 = np.arange(0,30).reshape(-1,2)
print(arr1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


In [51]:
arr2 = np.random.randint(0,100,60).reshape(2,5,-1)
print(f"Dizi:{arr2}\nŞekil:{arr2.shape}\nBoyut:{arr2.ndim}")

Dizi:[[[84 57 66  4 19 14]
  [90 68 16 75 32 70]
  [88  5  2  8 12  5]
  [39 13 89 53 60 34]
  [80  0  3 12 99 70]]

 [[75 20 68 68 31 10]
  [85  9 61 23 31 63]
  [36 70 16 93 79 71]
  [ 8 32 45 70 87  7]
  [33  1 75 88 21 88]]]
Şekil:(2, 5, 6)
Boyut:3


In [52]:
arr3 = np.random.randint(0,10,20).reshape(4,-1)
print(f"Dizi:{arr3}")
arr3 = arr3.reshape(-1)
print(f"Dizi:{arr3}\nŞekil:{arr3.shape}\nBoyut:{arr3.ndim}")

Dizi:[[9 4 4 6 3]
 [6 0 7 6 9]
 [8 8 4 1 7]
 [4 7 3 8 9]]
Dizi:[9 4 4 6 3 6 0 7 6 9 8 8 4 1 7 4 7 3 8 9]
Şekil:(20,)
Boyut:1


In [53]:
arr4 = np.arange(0,10).reshape(2,5)
for x in arr4 :
  for y in x :
    print(y)
print("\n")
for x in np.nditer(arr4) :
  print(x)

0
1
2
3
4
5
6
7
8
9


0
1
2
3
4
5
6
7
8
9


In [54]:
arr5 = np.array([5,10,15,20,25,30])
arr6 = np.array([1,2,3,4,5,6])
print(arr5 + arr6)
print(arr5 - arr6)
print(arr5 * arr6)
print(arr5 / arr6)

[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]


In [55]:
arr7 = np.random.randint(0,100,10)
print("Sum:", arr7.sum())
print("Mean:",arr7.mean())
print("Max:", arr7.max())
print("Var:", arr7.var())
print("Std:", arr7.std())

Sum: 499
Mean: 49.9
Max: 97
Var: 1133.8899999999999
Std: 33.67328317821118


In [56]:
arr8 = np.arange(0,20)
arr9 = np.arange(500,531)
print(np.concatenate([arr8, arr9]))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515
 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530]


In [57]:
arr10 = np.arange(15,51)
arr11 = np.arange(10,101)
arr12 = np.concatenate([arr10, arr11])
arr12[25:50] = 888
print(arr12)

[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [58]:
arr13 = np.arange(0,40).reshape(8,5)
arr14 = np.arange(320,360).reshape(8,5)
print(np.concatenate([arr13, arr14], axis = 0), end = '\n\n')
print(np.concatenate([arr13, arr14], axis = 1))
# Fark : Biri alt alta ilave ederken öteki yanına ekledi.

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]

[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


In [59]:
# print(np.concatenate([arr13, arr14], axis = 2), end = '\n\n')

In [60]:
print(np.stack([arr13, arr14], axis = 2), end = '\n\n')
# Biri hata verirken öteki yeni bir boyut oluşturdu.

[[[  0 320]
  [  1 321]
  [  2 322]
  [  3 323]
  [  4 324]]

 [[  5 325]
  [  6 326]
  [  7 327]
  [  8 328]
  [  9 329]]

 [[ 10 330]
  [ 11 331]
  [ 12 332]
  [ 13 333]
  [ 14 334]]

 [[ 15 335]
  [ 16 336]
  [ 17 337]
  [ 18 338]
  [ 19 339]]

 [[ 20 340]
  [ 21 341]
  [ 22 342]
  [ 23 343]
  [ 24 344]]

 [[ 25 345]
  [ 26 346]
  [ 27 347]
  [ 28 348]
  [ 29 349]]

 [[ 30 350]
  [ 31 351]
  [ 32 352]
  [ 33 353]
  [ 34 354]]

 [[ 35 355]
  [ 36 356]
  [ 37 357]
  [ 38 358]
  [ 39 359]]]



In [61]:
arr15 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
print(np.where(arr15 == 5), end = '\n\n')
print(np.where(arr15%2 == 0), end = '\n\n')
print(np.where(arr15 > 4), end = '\n\n')
print(np.where(arr15%5 == 0), end = '\n\n')

(array([ 5, 13]),)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

(array([ 1,  2,  5, 13]),)



In [62]:
x = np.random.randint(85,101)
x

100

In [63]:
arr16 = np.random.randint(10,100,(3,3))
print(arr16)

[[77 57 74]
 [72 75 41]
 [30 71 81]]


In [64]:
arr17 = np.arange(35,61)
print(np.random.choice(arr17))

48


In [65]:
arr18 = np.array([[3,8], [10, 53], [3,53], [10,3], [3,53]])
print(arr18)

[[ 3  8]
 [10 53]
 [ 3 53]
 [10  3]
 [ 3 53]]
