In [4]:
import numpy as np
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3d.ndim)

3


In [7]:
arr1 = np.arange(34,113,6)
print(arr1)

[ 34  40  46  52  58  64  70  76  82  88  94 100 106 112]


In [8]:
arr2 = np.linspace(50,500,91, dtype = 'int')
print(arr2)

[ 50  55  60  65  70  75  80  85  90  95 100 105 110 115 120 125 130 135
 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225
 230 235 240 245 250 255 260 265 270 275 280 285 290 295 300 305 310 315
 320 325 330 335 340 345 350 355 360 365 370 375 380 385 390 395 400 405
 410 415 420 425 430 435 440 445 450 455 460 465 470 475 480 485 490 495
 500]


In [14]:
arr3 = np.logspace(2,5,8)
print(arr3)

[   100.            268.26957953    719.685673     1930.69772888
   5179.47467923  13894.95494373  37275.93720315 100000.        ]


In [57]:
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
arr5 = np.zeros((6,6), dtype = 'int')
print(arr5)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [37]:
arr5 = np.ones((4,4), dtype = 'int')
print(arr5)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [51]:
arr6 = np.eye(8, dtype = 'int')
print(arr6)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [53]:
arr7 = np.eye(8) * 3
print(arr7)

[[3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3.]]


In [56]:
arr8 = np.random.rand(6)
print(arr8)

[0.84441177 0.4123653  0.82512792 0.04162789 0.30379101 0.94323499]


In [85]:
arr9 = np.random.randint(50,101,(2,5))
print(arr9)
print(arr9.shape)

[[69 53 74 77 89]
 [97 65 76 71 96]]
(2, 5)


In [87]:
arr10 = np.random.randint(100,1000,(2,5,5))
print(arr10)
print(arr10.ndim)
print(arr10.shape)

[[[525 238 756 972 328]
  [154 252 714 253 882]
  [218 997 636 278 656]
  [910 568 809 593 750]
  [105 262 221 487 322]]

 [[551 549 915 983 646]
  [130 201 131 756 899]
  [151 376 821 343 799]
  [467 174 238 302 243]
  [374 891 470 717 759]]]
3
(2, 5, 5)


In [91]:
arr11 = np.random.randint(0,100,10)
print(arr11)
print(arr11.max()) 
print(arr11.argmax()) 
print(arr11.min()) 
print(arr11.argmin())

[39 57 11 47 65 23 51 44 84 87]
87
9
11
2


In [93]:
arr12 = np.random.randint(300,501,(2,2,5))
print(arr12)

[[[368 342 400 412 301]
  [346 445 388 381 498]]

 [[439 457 429 474 419]
  [325 422 384 400 422]]]


In [95]:
print("Max:", arr12[0,1,4])
print("Min:", arr12[0,0,4])

Max: 498
Min: 301


In [98]:
arr13 = np.arange(0,51)
print(arr13)
arr13[20:35] = 500
print(arr13)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
